/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2026 DirazCoder
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.dirazcoder.crystalblocks.item;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import net.minecraft.block.Block;
import net.minecraft.block.BlockSlab;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemSlab;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

import com.dirazcoder.crystalblocks.block.ModBlocks;

// RegistryEvent.Register<Block> does NOT create an ItemBlock for free in
// 1.12.2 - that auto-creation never existed on this Forge version (it's
// easy to assume otherwise since GameRegistry.registerBlock did handle
// it back in 1.7.10). ItemBlocks need their own explicit pass through
// RegistryEvent.Register<Item>, same as any other item, confirmed
// against real "RegistryEvent.Register<ItemBlock> is also not a thing -
// you register ItemBlocks like any other item" guidance rather than
// assumed from the old registerBlock behavior.
//
// double slabs are skipped here on purpose - they're never craftable
// or holdable directly, only produced by stacking two singles, same as
// vanilla stone/wood double slabs, so they get no item form at all.
//
// crafting recipes are no longer registered from Java at all - they're
// JSON files under assets/crystalblocks/recipes/, auto-loaded by Forge,
// generated by generate_assets.py alongside the blockstates/models
@Mod.EventBusSubscriber
public class ModItems {

    @SubscribeEvent
    public static void registerItems(RegistryEvent.Register<Item> event) {
        List<Item> toRegister = new ArrayList<>();

        for (Map<String, Block> blocks : ModBlocks.BLOCKS_BY_FAMILY.values()) {
            addItemBlocks(toRegister, blocks);
        }
        for (String family : ModBlocks.SLABS_BY_FAMILY.keySet()) {
            addSlabItemBlocks(toRegister, ModBlocks.SLABS_BY_FAMILY.get(family), ModBlocks.DOUBLE_SLABS_BY_FAMILY.get(family));
        }
        // DOUBLE_SLABS_BY_FAMILY intentionally skipped as its own loop -
        // its blocks are only ever reached through the single slab's
        // ItemSlab above, same restriction as vanilla stone/wood slabs
        for (Map<String, Block> stairs : ModBlocks.STAIRS_BY_FAMILY.values()) {
            addItemBlocks(toRegister, stairs);
        }
        for (Map<String, Block> fences : ModBlocks.FENCES_BY_FAMILY.values()) {
            addItemBlocks(toRegister, fences);
        }
        for (Map<String, Block> fenceGates : ModBlocks.FENCE_GATES_BY_FAMILY.values()) {
            addItemBlocks(toRegister, fenceGates);
        }
        for (Map<String, Block> walls : ModBlocks.WALLS_BY_FAMILY.values()) {
            addItemBlocks(toRegister, walls);
        }

        for (Block glowBlock : ModBlocks.GLOW_BLOCKS_BY_FAMILY.values()) {
            toRegister.add(itemBlockFor(glowBlock));
        }
        for (String family : ModBlocks.GLOW_SLABS_BY_FAMILY.keySet()) {
            Block glowSlab = ModBlocks.GLOW_SLABS_BY_FAMILY.get(family);
            Block glowDoubleSlab = ModBlocks.GLOW_DOUBLE_SLABS_BY_FAMILY.get(family);
            toRegister.add(slabItemBlockFor(glowSlab, glowDoubleSlab));
        }
        // GLOW_DOUBLE_SLABS_BY_FAMILY intentionally skipped as its own
        // loop, same reasoning as DOUBLE_SLABS_BY_FAMILY above
        for (Block glowStairs : ModBlocks.GLOW_STAIRS_BY_FAMILY.values()) {
            toRegister.add(itemBlockFor(glowStairs));
        }

        event.getRegistry()
            .registerAll(toRegister.toArray(new Item[0]));
    }

    private static void addItemBlocks(List<Item> toRegister, Map<String, Block> blocksByColor) {
        for (Block block : blocksByColor.values()) {
            toRegister.add(itemBlockFor(block));
        }
    }

    // plain ItemBlock has no idea a double variant exists, so stacking a
    // second single slab on a placed one never merges them - that's what
    // vanilla's ItemSlab is for. It needs both slab instances up front to
    // recognize the placed block as "one of mine" and know what to swap
    // it for.
    private static void addSlabItemBlocks(List<Item> toRegister, Map<String, Block> singlesByColor,
            Map<String, Block> doublesByColor) {
        for (String color : singlesByColor.keySet()) {
            toRegister.add(slabItemBlockFor(singlesByColor.get(color), doublesByColor.get(color)));
        }
    }

    private static Item itemBlockFor(Block block) {
        return new ItemBlock(block).setRegistryName(block.getRegistryName());
    }

    private static Item slabItemBlockFor(Block singleSlab, Block doubleSlab) {
        return new ItemSlab(singleSlab, (BlockSlab) singleSlab, (BlockSlab) doubleSlab)
            .setRegistryName(singleSlab.getRegistryName());
    }
}
